exports.Fees = Object.freeze({
  SCHOOL_FEE: "SCHOOL FEE",
  HOSTEL_FEE: "HOSTEL FEE",
  MEDICAL_FEE: "MEDICAL FEE",
  SPORT_FEES: "SPORT FEES",
  TECHNOLOGY_FEE: "TECHNOLOGY FEE",
  SPORT_FEE: "SPORT FEE",
});
